[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17"
rocket = "0.5.0-rc.2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12"
serde_json = "1.0"
serde = "1.0"
